name: Run unit tests

on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: 17
      STREAM_PLAYGROUND_PATH: 'stream-playground'

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
      - name: Clone stream-playground
        uses: actions/checkout@v2
        with:
          repository: jeszy75/stream-playground
          path: ${{ env.STREAM_PLAYGROUND_PATH }}
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Install stream-playground
        working-directory: ${{ env.STREAM_PLAYGROUND_PATH }}
        run: mvn install
      - name: Execute unit tests
        run: mvn test
      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'